// Code generated by protoc-gen-go. DO NOT EDIT.
// source: salute/salute.proto

/*
Package salute is a generated protocol buffer package.

Define that the generated files will have the package salute

It is generated from these files:
	salute/salute.proto

It has these top-level messages:
	SaluteRequest
	SaluteResponse
*/
package salute

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ResponseType int32

const (
	ResponseType_HTML ResponseType = 0
	ResponseType_TEXT ResponseType = 1
)

var ResponseType_name = map[int32]string{
	0: "HTML",
	1: "TEXT",
}
var ResponseType_value = map[string]int32{
	"HTML": 0,
	"TEXT": 1,
}

func (x ResponseType) String() string {
	return proto.EnumName(ResponseType_name, int32(x))
}
func (ResponseType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type SaluteRequest struct {
	ResponseType ResponseType               `protobuf:"varint,1,opt,name=response_type,json=responseType,enum=salute.ResponseType" json:"response_type,omitempty"`
	Saluters     string                     `protobuf:"bytes,2,opt,name=saluters" json:"saluters,omitempty"`
	Salutee      string                     `protobuf:"bytes,3,opt,name=salutee" json:"salutee,omitempty"`
	VideoUrl     string                     `protobuf:"bytes,4,opt,name=video_url,json=videoUrl" json:"video_url,omitempty"`
	LogoUrl      string                     `protobuf:"bytes,5,opt,name=logo_url,json=logoUrl" json:"logo_url,omitempty"`
	Description  string                     `protobuf:"bytes,6,opt,name=description" json:"description,omitempty"`
	Url          string                     `protobuf:"bytes,7,opt,name=url" json:"url,omitempty"`
	Timestamp    *google_protobuf.Timestamp `protobuf:"bytes,8,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (m *SaluteRequest) Reset()                    { *m = SaluteRequest{} }
func (m *SaluteRequest) String() string            { return proto.CompactTextString(m) }
func (*SaluteRequest) ProtoMessage()               {}
func (*SaluteRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SaluteRequest) GetResponseType() ResponseType {
	if m != nil {
		return m.ResponseType
	}
	return ResponseType_HTML
}

func (m *SaluteRequest) GetSaluters() string {
	if m != nil {
		return m.Saluters
	}
	return ""
}

func (m *SaluteRequest) GetSalutee() string {
	if m != nil {
		return m.Salutee
	}
	return ""
}

func (m *SaluteRequest) GetVideoUrl() string {
	if m != nil {
		return m.VideoUrl
	}
	return ""
}

func (m *SaluteRequest) GetLogoUrl() string {
	if m != nil {
		return m.LogoUrl
	}
	return ""
}

func (m *SaluteRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *SaluteRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *SaluteRequest) GetTimestamp() *google_protobuf.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

type SaluteResponse struct {
	ResponseType ResponseType `protobuf:"varint,1,opt,name=response_type,json=responseType,enum=salute.ResponseType" json:"response_type,omitempty"`
	Body         string       `protobuf:"bytes,2,opt,name=body" json:"body,omitempty"`
}

func (m *SaluteResponse) Reset()                    { *m = SaluteResponse{} }
func (m *SaluteResponse) String() string            { return proto.CompactTextString(m) }
func (*SaluteResponse) ProtoMessage()               {}
func (*SaluteResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *SaluteResponse) GetResponseType() ResponseType {
	if m != nil {
		return m.ResponseType
	}
	return ResponseType_HTML
}

func (m *SaluteResponse) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func init() {
	proto.RegisterType((*SaluteRequest)(nil), "salute.SaluteRequest")
	proto.RegisterType((*SaluteResponse)(nil), "salute.SaluteResponse")
	proto.RegisterEnum("salute.ResponseType", ResponseType_name, ResponseType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Saluter service

type SaluterClient interface {
	Salute(ctx context.Context, in *SaluteRequest, opts ...grpc.CallOption) (*SaluteResponse, error)
}

type saluterClient struct {
	cc *grpc.ClientConn
}

func NewSaluterClient(cc *grpc.ClientConn) SaluterClient {
	return &saluterClient{cc}
}

func (c *saluterClient) Salute(ctx context.Context, in *SaluteRequest, opts ...grpc.CallOption) (*SaluteResponse, error) {
	out := new(SaluteResponse)
	err := grpc.Invoke(ctx, "/salute.Saluter/Salute", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Saluter service

type SaluterServer interface {
	Salute(context.Context, *SaluteRequest) (*SaluteResponse, error)
}

func RegisterSaluterServer(s *grpc.Server, srv SaluterServer) {
	s.RegisterService(&_Saluter_serviceDesc, srv)
}

func _Saluter_Salute_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaluteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SaluterServer).Salute(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/salute.Saluter/Salute",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SaluterServer).Salute(ctx, req.(*SaluteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Saluter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "salute.Saluter",
	HandlerType: (*SaluterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Salute",
			Handler:    _Saluter_Salute_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "salute/salute.proto",
}

func init() { proto.RegisterFile("salute/salute.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 312 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x51, 0x4b, 0x4f, 0xc2, 0x40,
	0x10, 0xb6, 0x80, 0xa5, 0x0c, 0x8f, 0x90, 0xf1, 0x91, 0xb5, 0x1e, 0x6c, 0x38, 0x11, 0x0f, 0x25,
	0xc1, 0x83, 0x7a, 0x35, 0x31, 0xf1, 0xa0, 0x97, 0x5a, 0x13, 0x6f, 0x04, 0x64, 0x24, 0x4d, 0x0a,
	0xbb, 0xee, 0x6e, 0x4d, 0xf8, 0x43, 0xfe, 0x4e, 0xd3, 0x1d, 0x8a, 0xd5, 0xab, 0xa7, 0x7e, 0xcf,
	0x6e, 0xf7, 0x2b, 0x1c, 0x99, 0x79, 0x5e, 0x58, 0x9a, 0xf0, 0x23, 0x56, 0x5a, 0x5a, 0x89, 0x3e,
	0xb3, 0xf0, 0x62, 0x25, 0xe5, 0x2a, 0xa7, 0x89, 0x53, 0x17, 0xc5, 0xfb, 0xc4, 0x66, 0x6b, 0x32,
	0x76, 0xbe, 0x56, 0x1c, 0x1c, 0x7d, 0x35, 0xa0, 0xff, 0xec, 0xb2, 0x09, 0x7d, 0x14, 0x64, 0x2c,
	0xde, 0x42, 0x5f, 0x93, 0x51, 0x72, 0x63, 0x68, 0x66, 0xb7, 0x8a, 0x84, 0x17, 0x79, 0xe3, 0xc1,
	0xf4, 0x38, 0xde, 0x1d, 0x90, 0xec, 0xcc, 0x74, 0xab, 0x28, 0xe9, 0xe9, 0x1a, 0xc3, 0x10, 0x02,
	0x0e, 0x69, 0x23, 0x1a, 0x91, 0x37, 0xee, 0x24, 0x7b, 0x8e, 0x02, 0xda, 0x8c, 0x49, 0x34, 0x9d,
	0x55, 0x51, 0x3c, 0x87, 0xce, 0x67, 0xb6, 0x24, 0x39, 0x2b, 0x74, 0x2e, 0x5a, 0x5c, 0x73, 0xc2,
	0x8b, 0xce, 0xf1, 0x0c, 0x82, 0x5c, 0xae, 0xd8, 0x3b, 0xe4, 0x5e, 0xc9, 0x4b, 0x2b, 0x82, 0xee,
	0x92, 0xcc, 0x9b, 0xce, 0x94, 0xcd, 0xe4, 0x46, 0xf8, 0xce, 0xad, 0x4b, 0x38, 0x84, 0x66, 0xd9,
	0x6b, 0x3b, 0xa7, 0x84, 0x78, 0x03, 0x9d, 0xfd, 0x02, 0x22, 0x88, 0xbc, 0x71, 0x77, 0x1a, 0xc6,
	0xbc, 0x51, 0x5c, 0x6d, 0x14, 0xa7, 0x55, 0x22, 0xf9, 0x09, 0x8f, 0x66, 0x30, 0xa8, 0x76, 0xe2,
	0x1b, 0xff, 0x67, 0x28, 0x84, 0xd6, 0x42, 0x2e, 0xb7, 0xbb, 0x91, 0x1c, 0xbe, 0x1c, 0x41, 0xaf,
	0xde, 0xc0, 0x00, 0x5a, 0x0f, 0xe9, 0xd3, 0xe3, 0xf0, 0xa0, 0x44, 0xe9, 0xfd, 0x6b, 0x3a, 0xf4,
	0xa6, 0x77, 0xd0, 0xe6, 0x8f, 0xd0, 0x78, 0x0d, 0x3e, 0x43, 0x3c, 0xa9, 0x0e, 0xfc, 0xf5, 0x1f,
	0xc3, 0xd3, 0xbf, 0x32, 0xbf, 0x7b, 0xe1, 0xbb, 0x7b, 0x5e, 0x7d, 0x07, 0x00, 0x00, 0xff, 0xff,
	0x99, 0x07, 0x3c, 0x47, 0x38, 0x02, 0x00, 0x00,
}
